name: ArLibs
version: ${version}
main: com.arteam.arlibs.ArLibs
api-version: '1.20'
authors: [ArteamTech]
description: A powerful library plugin for Minecraft servers
website: https://github.com/ArteamTech/ArLibs